# Generated by Django 5.2.11 on 2026-08-10 02:00

import django.db.models.deletion
import flightlogs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_backuplog_0003_businessfeature'),
        ('flightlogs', '0002_flightlog_takeoff_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('dji_txt', 'DJI FlightRecord')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=flightlogs.models.dji_source_upload_path)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('safe_error_code', models.CharField(blank=True, max_length=64)),
                ('safe_error_detail', models.CharField(blank=True, max_length=255)),
                ('parser_version', models.CharField(blank=True, max_length=32)),
                ('log_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('encrypted', models.BooleanField(blank=True, null=True)),
                ('aircraft_model_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aircraft_serial', models.CharField(blank=True, max_length=100)),
                ('aircraft_serial_header', models.CharField(blank=True, max_length=100)),
                ('battery_serial', models.CharField(blank=True, max_length=100)),
                ('battery_serial_header', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flightlog_sources_created', to=settings.AUTH_USER_MODEL)),
                ('flight_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='flightlogs.flightlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='flightlogs__busines_809d90_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'sha256'), name='uniq_flightlog_source_business_sha256')],
            },
        ),
    ]
