# Generated by Django 5.2.11 on 2026-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightlogs', '0003_flightlogsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='battery_cycle_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='battery_life_raw',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='camera_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='dji_serious_warnings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='dji_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='dji_warnings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='flight_modes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='maximum_cell_voltage_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='maximum_satellites',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='maximum_vertical_speed_mps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='minimum_airborne_gps_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='minimum_airborne_satellites',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='minimum_cell_voltage_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='rc_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
