# Generated by Django 5.2.11 on 2026-08-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_manufacturer_asset_model_asset_serial_number_and_more'),
        ('flightlogs', '0006_flightlog_takeoff_city_flightlog_takeoff_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='aircraft_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_logs', to='assets.aircraftmodel'),
        ),
    ]
