# Generated by Django 5.2.11 on 2026-08-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drones", "0001_initial"),
        ("flightlogs", "0007_flightlog_aircraft_model"),
    ]
    operations = [
        migrations.AddField(
            model_name="flightlog",
            name="drone_model",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="flight_logs", to="drones.dronemodel"),
        ),
    ]
