# Generated by Django 5.2.11 on 2026-08-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_faa_registration'),
        ('flightlogs', '0008_flightlog_drone_model'),
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_logs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_logs', to='pilot.pilotprofile'),
        ),
    ]
