# Generated by ChatGPT patch for recurring expenses.
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_assets_asse_busines_d2219d_idx_assets_asse_busines_624ed1_idx_and_more'),
        ('core', '0004_merge_0003_backuplog_0003_businessfeature'),
        ('vehicles', '0005_rename_vehicles_ve_busines_loanpd_idx_vehicles_ve_busines_ad11d0_idx'),
        ('ledger', '0003_vehicle_subcategory_requires_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('trans_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('journal', 'Journal Only')], editable=False, max_length=10)),
                ('is_refund', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=25)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/recurring_expenses/')),
                ('transport_type', models.CharField(blank=True, choices=[('', '—'), ('personal_vehicle', 'Personal vehicle'), ('rental_car', 'Rental car'), ('business_vehicle', 'Business vehicle')], default='', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Used when advancing monthly or quarterly expenses.')),
                ('next_run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='assets.asset')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('category', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='ledger.category')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='ledger.contact')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='ledger.job')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='ledger.subcategory')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='ledger.team')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['next_run_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('recurring_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ledger.recurringexpense')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_runs', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-run_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringexpenserun',
            index=models.Index(fields=['business', 'recurring_expense', 'run_date'], name='ledger_recu_busines_2634e0_idx'),
        ),
    ]
