# Generated by Django 5.2.11 on 2026-08-02 22:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recurring_expenses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringexpenserun',
            new_name='ledger_recu_busines_367c0f_idx',
            old_name='ledger_recu_busines_2634e0_idx',
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
