# Generated by Django 5.2.11 on 2026-09-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_rename_ledger_recu_busines_2634e0_idx_ledger_recu_busines_367c0f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-is_active', '-job_year', '-job_seq', 'label']},
        ),
    ]
