# Generated by Django 5.2.11 on 2026-05-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assettype_active_remove_vehicle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_busines_624ed1_idx',
            old_name='assets_asse_busines_d2219d_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_busines_620d2e_idx',
            old_name='assets_asse_busines_705612_idx',
        ),
        migrations.RenameIndex(
            model_name='assettype',
            new_name='assets_asse_busines_fb2138_idx',
            old_name='assets_asse_busines_7d2e48_idx',
        ),
    ]
