# Generated by Django 5.2.11 on 2026-08-12 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_assets_asse_busines_d2219d_idx_assets_asse_busines_624ed1_idx_and_more'),
        ('core', '0004_merge_0003_backuplog_0003_businessfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.SlugField(editable=False, max_length=180)),
                ('dji_model_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='aircraft_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='assets.aircraftmodel'),
        ),
        migrations.AddConstraint(
            model_name='aircraftmodel',
            constraint=models.UniqueConstraint(fields=('business', 'normalized_name'), name='uniq_aircraft_model_business_name'),
        ),
        migrations.AddConstraint(
            model_name='aircraftmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('dji_model_code__isnull', False)), fields=('business', 'dji_model_code'), name='uniq_aircraft_model_business_dji_code'),
        ),
    ]
