# Generated by Django 5.2.11 on 2026-08-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_asset_manufacturer_asset_model_asset_serial_number_and_more"),
        ("drones", "0001_initial"),
    ]
    operations = [
        migrations.AddField(
            model_name="asset",
            name="drone_model",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="equipment", to="drones.dronemodel"),
        ),
    ]
