# Generated by Django 5.2.11 on 2026-08-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_drone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='faa_registration',
            field=models.CharField(blank=True, help_text='FAA aircraft registration number, if applicable.', max_length=100),
        ),
    ]
