# Generated by Django 5.2.11 on 2026-08-12 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="BatteryFamily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("manufacturer", models.CharField(max_length=100)),
                ("normalized_manufacturer", models.SlugField(editable=False, max_length=120)),
                ("name", models.CharField(max_length=150)),
                ("normalized_name", models.SlugField(editable=False, max_length=180)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Battery families",
                "ordering": ["manufacturer", "name"],
                "constraints": [models.UniqueConstraint(fields=("normalized_manufacturer", "normalized_name"), name="uniq_drone_battery_family_name")],
            },
        ),
        migrations.CreateModel(
            name="DroneModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("manufacturer", models.CharField(max_length=100)),
                ("normalized_manufacturer", models.SlugField(editable=False, max_length=120)),
                ("name", models.CharField(max_length=150)),
                ("normalized_name", models.SlugField(editable=False, max_length=180)),
                ("full_display_name", models.CharField(editable=False, max_length=255)),
                ("year_released", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_enterprise", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("battery_family", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="drone_models", to="drones.batteryfamily")),
            ],
            options={"ordering": ["manufacturer", "name"]},
        ),
        migrations.CreateModel(
            name="DroneModelAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alias", models.CharField(max_length=255)),
                ("normalized_alias", models.SlugField(editable=False, max_length=255, unique=True)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("drone_model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="drones.dronemodel")),
            ],
            options={"verbose_name_plural": "Drone model aliases", "ordering": ["alias"]},
        ),
        migrations.CreateModel(
            name="DroneModelIdentifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=50)),
                ("normalized_provider", models.SlugField(editable=False, max_length=60)),
                ("identifier", models.CharField(max_length=255)),
                ("normalized_identifier", models.CharField(editable=False, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("drone_model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="identifiers", to="drones.dronemodel")),
            ],
            options={"ordering": ["provider", "identifier"]},
        ),
        migrations.CreateModel(
            name="DroneSafetyProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("safety_features", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drone_model", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="safety_profile", to="drones.dronemodel")),
            ],
            options={"ordering": ["drone_model__manufacturer", "drone_model__name"]},
        ),
        migrations.AddConstraint(
            model_name="dronemodel",
            constraint=models.UniqueConstraint(fields=("normalized_manufacturer", "normalized_name"), name="uniq_drone_model_manufacturer_name"),
        ),
        migrations.AddConstraint(
            model_name="dronemodelidentifier",
            constraint=models.UniqueConstraint(fields=("normalized_provider", "normalized_identifier"), name="uniq_drone_provider_identifier"),
        ),
    ]
